In [4]:
import numpy as np


In [5]:
salary=np.random.randint(1000,20000,10)

In [6]:
salary

array([15238,  7799,  4623, 19057,  6081, 17397,  5793, 13144, 16157,
        4689])

In [7]:
#set minimum and maximum salary using a_min and a_max 

In [8]:
np.clip(salary,a_min=2000,a_max=10000)

array([10000,  7799,  4623, 10000,  6081, 10000,  5793, 10000, 10000,
        4689])

In [9]:
#If you want to find actual salary which are less then or greater than some salary use np.where
#np.where gives index detail

In [11]:
print(np.where(salary >5000))

(array([0, 1, 3, 4, 5, 6, 7, 8], dtype=int64),)


In [12]:
#If you want to see actual data, use index

In [13]:
salary[[1,5]]

array([ 7799, 17397])

In [14]:

#similarly you can  check for any condition (<,>,=,==,<=,>=)

In [19]:
print(np.where(salary ==2000))

(array([], dtype=int64),)


In [20]:
print(np.where(salary >=5000))

(array([0, 1, 3, 4, 5, 6, 7, 8], dtype=int64),)


In [21]:
print(np.where(salary < 15000))

(array([1, 2, 4, 6, 7, 9], dtype=int64),)


In [24]:

#Reshaping Otherways

In [22]:
import numpy as np
from numpy.random import randint as ri

In [23]:
a=ri(200,300,30)
print(a)

[296 238 230 248 211 232 224 232 228 277 277 208 263 207 278 264 250 246
 253 285 245 242 206 219 234 282 296 211 256 289]


In [26]:

b=a.reshape(2,3,5)
print(b)

[[[296 238 230 248 211]
  [232 224 232 228 277]
  [277 208 263 207 278]]

 [[264 250 246 253 285]
  [245 242 206 219 234]
  [282 296 211 256 289]]]


In [28]:
print("Minimum of a is ",b.min())  # find minimum value 
print("Maximum of a is ",b.max())  # find maximum value

Minimum of a is  206
Maximum of a is  296


In [31]:
m=ri(1,1000,25).reshape(5,5) #matrix of random integer

In [32]:
m

array([[950, 242, 679, 810, 758],
       [726, 607,  23, 775, 252],
       [828, 314,  36, 518, 525],
       [214, 366, 290, 425, 190],
       [248,  31, 187, 785,  12]])

In [33]:
# Index and slicing

In [34]:
arr=np.arange(20,30)
print("Array",arr)

Array [20 21 22 23 24 25 26 27 28 29]


In [35]:
print("Element of 7th index is =",arr[6])

Element of 7th index is = 26


In [36]:

print("Element of 3rd and 5th index is = ",arr[3:4])

Element of 3rd and 5th index is =  [23]


In [37]:
#Store arr in abc and check upto 4th index of abc

In [38]:
aman=arr[5:]
print(aman)

[25 26 27 28 29]


In [41]:
print("Element from last backwords : ",aman[-1::-1])

Element from last backwords :  [29 28 27 26 25]


In [42]:

my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print("Entire row at index 1: ",mat[1])

Entire row at index 1:  [4 5 6]


In [46]:
#Subsetting-So what is subsetting ? subsetting means when we wann to fetch only few dara from matrix then we use subsetting method.

In [48]:
mat=np.array(ri(5,50,15)).reshape(3,5)


In [49]:
mat

array([[ 8, 38, 14, 23, 36],
       [46, 43, 14, 42, 23],
       [49, 35, 30, 27, 41]])

In [50]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

In [53]:
print(mat1)
print(mat2)

[[6 1 2]
 [9 6 8]
 [6 2 2]]
[[9 6 3]
 [8 3 5]
 [3 7 7]]


In [54]:

#Broadcasting-
#Numpy operations are usually dont on pairs of arrays on an element by element basis. in the simplest case, the two arays must have exactly the same shape
# Numpy broadcasting rules relaxex this constraints when the array shape meet certain constraints when operatings on two array,
# Numpy compares their shape element wise it starts with the trailing dimensions ,and word its way forword ,two dimension are compatible
#when they are eqaul,or one of them is 1

In [55]:
start=np.zeros((5,5))
print(start)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [56]:

#create a rank1 ndarray with 3 values

In [59]:

add_rows=np.array([[2,4,6]])
print(add_rows)

[[2 4 6]]


In [61]:
new_row=add_rows.T  # t is use to transpose 

In [62]:

new_row

array([[2],
       [4],
       [6]])