# Numpy

#### NumPy is a powerful library in Python for numerical computing. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures

NumPy offers a wide range of functions for array creation, manipulation, and mathematical operations

In [2]:
#importing Numpy
import numpy as np

In [4]:
np.sqrt(25) # sqrt = square root

5.0

In [5]:
np.sqrt(12) 

3.4641016151377544

In [7]:
print("Maximum" , np.amax([12,40,112,909]))   #  find maximum value

Maximum 909


In [8]:
print("minimum" , np.amin([12,40,89,200]))  # find minimum value

minimum 12


#### Ceil function :  the ceil function returns the smallest integer greater than or equal to a given number. This can be achieved using the math module's ceil function.

In [12]:
import math
number = 4.2
ceiling_value = math.ceil(number)
print(ceiling_value)  


5


In [13]:
import numpy as np
array = np.array([1.1, 2.5, 3.3, 4.9])
ceiling_array = np.ceil(array)
print(ceiling_array)


[2. 3. 4. 5.]


In [14]:
np.ceil(3.1)

4.0

In [16]:
np.ceil(4.9)    # its means when we use ceil they given roundfigure answer.

5.0

In [18]:
np.ceil(np.sqrt(41))  # find the sqare root then after find ceil value

7.0

In [21]:
np.ceil(np.sum(np.sqrt([50, 40, 5])))  # 

16.0

In [23]:
print(dir(np))   

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [28]:
import numpy as array
np.array([10,5,34])

array([10,  5, 34])

In [33]:
type([array])  # check the type 

list

In [34]:
abc = np.array([23,90,56]) # check the type of array
type (abc)

numpy.ndarray

In [32]:

a=np.array([[[1,22],[2,4],[11,43]]])
print("Type - ",a.dtype)

print("\n",a)

Type -  int32

 [[[ 1 22]
  [ 2  4]
  [11 43]]]


In [35]:
# dtype.conversion 

In [36]:
np.array([10,20,30],dtype=float)

array([10., 20., 30.])

In [37]:

#Covert a list into an array :

In [38]:
a = [11,22]
c = np.array(a)
print(c)

[11 22]


In [39]:
type(c)

numpy.ndarray

In [40]:
#copy array into other

In [42]:
s=np.asarray(c)
print(s)

[11 22]


In [43]:

# Data Types

In [44]:

import numpy as np


In [45]:

my_mat=[[3,24,10],[40,50,60],[70,80,90]]
mat=np.array(my_mat)
print("Type/class of this object : ",type(mat))
print("Here is the marks \n------\n",mat,"\n-----------")
print("print dimension of this matrix : ",mat.ndim)#ndim gives dimension,2 for a matrix and 1 for vector
print("size of the matrix : ",mat.size)#size shows total number elements
print("Shape of the matrix : ",mat.shape)#shape shows how many rows and column
print("Data Type of the matrix ; ",mat.dtype)#shoes which type

Type/class of this object :  <class 'numpy.ndarray'>
Here is the marks 
------
 [[ 3 24 10]
 [40 50 60]
 [70 80 90]] 
-----------
print dimension of this matrix :  2
size of the matrix :  9
Shape of the matrix :  (3, 3)
Data Type of the matrix ;  int32


In [46]:

#arange and linespace 

In [47]:
a=np.arange(100)

In [48]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [49]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [50]:

#Reverse Order

In [51]:
print("Every 10th number from 100 in reverse order \n",np.arange(100,-1,-10))

Every 10th number from 100 in reverse order 
 [100  90  80  70  60  50  40  30  20  10   0]


In [52]:

print("linearly space numbers between 1 and 50 \n-------------")
print(np.linspace(50,10,5))

linearly space numbers between 1 and 50 
-------------
[50. 40. 30. 20. 10.]


In [53]:

#Include end points and check space between the points
#By default endpoint=True
#Bydefaul retstep=False


In [55]:
np.linspace(5.0,10.0,num=4,endpoint=True,retstep=True)   # retstep = difference between first and second number 

(array([ 5.        ,  6.66666667,  8.33333333, 10.        ]),
 1.6666666666666667)

In [56]:

print(np.linspace(10.45,25.9865,39,retstep=True))

(array([10.45      , 10.85885526, 11.26771053, 11.67656579, 12.08542105,
       12.49427632, 12.90313158, 13.31198684, 13.72084211, 14.12969737,
       14.53855263, 14.94740789, 15.35626316, 15.76511842, 16.17397368,
       16.58282895, 16.99168421, 17.40053947, 17.80939474, 18.21825   ,
       18.62710526, 19.03596053, 19.44481579, 19.85367105, 20.26252632,
       20.67138158, 21.08023684, 21.48909211, 21.89794737, 22.30680263,
       22.71565789, 23.12451316, 23.53336842, 23.94222368, 24.35107895,
       24.75993421, 25.16878947, 25.57764474, 25.9865    ]), 0.4088552631578947)


In [57]:

#Matrics creation

In [58]:

print("vector of zeros \n")
print(np.zeros([10]))

vector of zeros 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [59]:

print("vector of zeros \n------------")
print(np.zeros([10,5]))

vector of zeros 
------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [60]:

print("vector of zeros \n------------")
print(np.zeros([5,4,6]))

vector of zeros 
------------
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [63]:

#Lets Try with Ones

#This tecniques only work with zero and ones if you want to print another number then use .below given technique

In [62]:

print("vector of ones \n")
print(np.ones([5,4]))

vector of ones 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [64]:

print("matrix of 5 \n--------")
print(5*np.ones([2,2]))

matrix of 5 
--------
[[5. 5.]
 [5. 5.]]


In [65]:
#Construct diagonal matrix


In [68]:

x=np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [69]:
#Random Number Generation

In [70]:
np.random.seed(6) # Each seed number will generate similar data
print("Random number genration (from uniform distribution)")
print(np.random.rand(7,5))

Random number genration (from uniform distribution)
[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668]
 [0.59505206 0.52981736 0.41880743 0.33540785 0.62251943]
 [0.43814143 0.73588211 0.51803641 0.5788586  0.6453551 ]
 [0.99022427 0.8198582  0.41320093 0.87626766 0.82375943]
 [0.05447451 0.71863724 0.80217056 0.73640664 0.70913175]
 [0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591]]


In [71]:
print("Number from normal distribution with zero mean and standard deviation 1 i.e standard noraml")
print(np.random.randn(7,5))

Number from normal distribution with zero mean and standard deviation 1 i.e standard noraml
[[ 0.27473356  0.13652337 -1.27492685 -0.76687441  1.48137821]
 [-0.5860804  -0.65666684  1.56711318 -0.02575935  0.25466512]
 [ 1.44853789 -0.87198626 -0.1840664  -0.75624874  0.73663324]
 [ 0.75368908 -0.86692034 -0.60354963 -2.05956406 -0.35843006]
 [-0.79742357  0.6020828   0.92508324 -0.45389277  0.89475268]
 [ 0.26713641  0.4312979  -1.16256293 -2.47133677 -0.61603672]
 [ 0.73343111  0.54429857 -0.82047949  0.41675765 -0.31114142]]


In [72]:

print("Random integer vector : ",np.random.randint(6,10,10))

Random integer vector :  [6 8 7 9 6 6 7 6 7 9]


In [73]:
print("\n Random integer matrix")    # choose the random values from given values
print(np.random.randint(1,300,(5,5)))


 Random integer matrix
[[  8 229 217  78  40]
 [121 235  77 173 121]
 [205 239 152 177 296]
 [220  38 108 127 290]
 [279  52 296 262  58]]


In [74]:
def generate_otp():
    otp=np.random.randint(999,99999,1)
    print("Your Otp is ",otp)
    user_otp=int(input("Enter Your OTP Here"))
    if otp==user_otp:
        print("Log in Sucessfully")
    else:
        print("Your OTP is invalid")

In [75]:
generate_otp()

Your Otp is  [46175]


Enter Your OTP Here 46175


Log in Sucessfully
